[package]
name = "SingularityRS"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
serde_yaml = "0.9.34+deprecated"
csv = "1.3.1"
xml-rs = "0.8.25"
serde = { version = "1.0.217", features = ["derive"] }
